### ISSUE TITLE
Make a new vignette about data specifications

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#118]
Create a new vignette that outlines details about the data used in the analysis. Details to include:

- a detailed explanation of what the data is about and its purpose 
- note if the data is required or optional - if it is option comment on the likelihood that this data exists/is accessible
- accepted file formats
- potential data sources/suggestions for finding the data

Information from app_vignette.Rmd > "Use the app with real data" can be moved to this document. 

This would allow for a more advanced overview of data specifications. This could allow for the other vignettes to be simplified/tailored towards beginners, directing more advanced users to this new documentation.

**Comment by adricaswell** [comment]
Make a comment in this vignette about how using different climate data will impact the ability to compare the indices to indices obtained using the NatureServe excel tool. And more generally the ability to compare the index results when different climate data is used.

**Comment by see24** [comment]
See Adriana's links to potential data sources here https://docs.google.com/document/d/1-dnesMN5eoc-14jXRBNAyVMkQ5oScAq-6MhrlzfD0tQ/edit
