### ISSUE TITLE
Add data source recommendations to Preparing custom climate data documentation

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#120]
Suggest [AdaptWest](https://adaptwest.databasin.org/pages/adaptwest-climatena/) as a source for climate data to users in the "Preparing custom climate data" documentation as was done in the "Using the ccviR package". Alternatively, suggestion could be added directly to the new documentation outlined in issue #118.

**Comment by see24** [comment]
There is actually a section in the app with a recommendation for where to get data. I think this should be moved to the documentation and replaced with a link to the docs in the app.
