### ISSUE TITLE
Add section about combining multiple species to Using the ccviR package vignette

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#122]
Add section outlining how to combine results of multiple species to package_vignette.Rmd. This section should act as a conclusion for the vignette so the end isn't so abrupt.

**Comment by see24** [comment]
I added a sentence about this at the end of the vignette but I think it could use more. Including a demo of a comparison

**Comment by see24** [comment]
I think this is enough really, users of the R package presumably know how to iterate and combine multiple data frames
