### ISSUE TITLE
Improve guideline pop-ups to ensure alignment with NS 3.02

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#125]
Make the pop ups providing additional information for the Vulnerability Questions in the app more readable. To do this, create a lookup table with all necessary information for each question that can then be referenced as needed. Use HTML formatting for the lookup table to format the pop ups as desired.

**Comment by adricaswell** [comment]
Most of the URLs in the NatureServe guidelines are broken. URLs in "Applying the Index" for Section B, C, and D should be included in the guideline lookup table for the help pop ups. Need to go through and fix the URLs. 

Once fixed, add to the guideline lu table. Use HTML formatting to create hyperlinks (formatting is already outlined in guideline_lu_tbl.R, just need to add link). Will also need to copy information about "Tools" to guideline_lu_tbl.R (was removed for the time being since links were broken, formatting is already in place, just need to add text). 

Be sure to reference Canadian guidelines for Canada specific tools!

**Comment by adricaswell** [comment]
Links for B2a and C3 were unable to be fixed due to the content no longer existing (or I was just not able to find it anywhere). 

B1 also didn't exist, but I was able to find a similar source. It is not referenced in the NatureServe Guidelines so unsure how to go about referencing it or if it is even necessary to do so. Could also just remove the link for this section.

**Comment by adricaswell** [comment]
Guidelines in the lookup table seem to be outdated (?) and US specific. In some areas, the text did not match the v3.02 Guidelines or the Canadian 3.0 Guidelines. While formatting, "Tools" text and select other text with links were changed to follow the Canadian 3.0 Guidelines. Which guidelines does ccviR refer to? And is it important that the popups follow that set of guidelines exclusively?

**Comment by see24** [comment]
I used the guidelines as written in the excel spread sheet for the US version of 3.02. I had hoped they would match with the pdf guidelines but if that is not the case you will need to pick one. Ideally the guidelines in our tool would work for all of North America. So including Canadian specific information would be good but I would include the American versions as well if they are available

**Comment by see24** [comment]
Also add pop-ups to the spatial data that gives more details on what is needed.
