### ISSUE TITLE
Improve the exposure results tables in app

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#127]
Make the exposure results tables easier to read/interpret. Undecided exactly how tables should be formatted - see below for some ideas. 
Option 1:
<img width="616" alt="image" src="https://github.com/LandSciTech/ccviR/assets/156369160/ad347a7d-bf7a-4f9f-9a05-e75bea2149ab">

Option 2:
<img width="616" alt="image" src="https://github.com/LandSciTech/ccviR/assets/156369160/2c13c11f-00db-499e-8ac4-32053b43fd20">

Additional table with exp multiplier
<img width="616" alt="image" src="https://github.com/LandSciTech/ccviR/assets/156369160/7aeaa63a-f9dc-4ce3-bc07-1041b0de37d6">

**Comment by see24** [comment]
Similar to option 1:
![image](https://github.com/LandSciTech/ccviR/assets/39161074/5bb6fb76-1f57-40d1-a6c3-b89b53ef8f13)

**Comment by adricaswell** [comment]
Reformatted table to improve readability using gt(). In theory, it should work. 

However, when creating a climate data set with three scenarios for testing, uncovered an issue where the brks_cmd and brks_mat from the climate_data_readme (used for the *change and *class column) are not identical if the processed data doesn't have the same highest and lowest value. As a result, will have to adjust how the get_exposure_table function combines the breaks for multiple scenarios. Currently using unique(), but since the character strings aren't identical, they won't merge.

![image](https://github.com/LandSciTech/ccviR/assets/156369160/93520047-f73e-450d-be6d-98a0e070bab9)

Will want to display the highest high value and the lowest low value.

**Comment by see24** [comment]
This is actually more of an issue with how the breaks are created I think. All scenarios ought to have the same breaks if they are being used to create comparable scenarios. It looks like they are using the same breaks for all but the min and max. So maybe the issue is just with recording the breaks in the climate readme csv. How did you process the climate data? with the app?

**Comment by see24** [comment]
If for some reason a user intentionally used different breaks for different scenarios we would want that to be clear in the table.

If the function detects different breaks I think the table should have a long format where it has a subsection of the table for each scenario with different breaks.

I will look in to making sure that when the same breaks are used the labels are correctly made the same across scenarios with different min and max values
