### ISSUE TITLE
Update demo climate data

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#129]
`output$texp_tbl` and `output$cmd_tbl` in ccvi_app.R refer to `clim_readme()$brks_cmd`, however, the brks_cmd column does not exist in the climate_data_readme.csv in the demo data set. In the dataset recently retrieved from [ccviR_Data_Packages](https://drive.google.com/drive/folders/18mO5GDUmwi-nswhIAC36bmtYsvmqNQkH), this column exists. Leading me to believe that the demo climate data (or at least the climate_data_readme.csv) needs to be updated based on changes to code. 

This discrepancy results in the an error in the Exposure Results tab (see screenshot)- "Error: `string` must be a single string, not `NULL`." 

Update demo dataset to prevent this error. 

<img width="585" alt="image" src="https://github.com/LandSciTech/ccviR/assets/156369160/70ba6d97-a9aa-4f2f-8c2a-aa60e6a3f1e4">

(temperature exposure has the same issue)

**Comment by see24** [comment]
I think I just fixed this! Try installing again from github. If it is resolved you can close the issue
