### ISSUE TITLE
Determine reason for persistent range change raster classification error and resolve

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#130]
When raster is input as a range change raster with the wrong classification the following error is produced: `Error: Reclassified range change raster values outside the expected range of 0-3 were found. Check that all range change raster values are included in the reclassification matrix`

In response to this error, I changed my input from  "Yes, one range change raster will be supplied for all scenarios" to "No [range change raster will be supplied]" as I decided that I will no longer be providing a range change raster (since it produced the error). However, re-running spatial analysis continues to produce this error, despite no range change raster being provided. 

The only way I found that I could resolve this error was to input an acceptable range change raster classification (or a raster that works with the input range change raster classification) and re-run spatial analysis - however, this would not be an option for someone who does not have an alternate range change raster or does not understand how to adjust the classification matrix to match the raster (which would be likely in this scenario). 

**ACTION**: Determine why this error persists without a range change raster input and address it to prevent the persistence of this error when input is changed.

In this case I found the wrong classification to be any classification where the all the raster values were not included. For example, for a raster with values ranging from 2-6:

- (No Error) Lost = from 2 to 3, maintained = from 4 to 5, gained = from 6 to 6, and not suitable = from 99 to 99
- (Error) Lost = from 2 to 2, maintained = from 4 to 4, gained = from 6 to 6, and not suitable = from 99 to 99
- (Error) Default values

Note: this does not seem to be an issue with the demo range change raster. This issue was discovered using `CMD_reclass_RCP_4.5.tiff` as a range change raster.

**Comment by see24** [comment]
Need to make the changing of the drop down remove the file as well as clicking the x
