### ISSUE TITLE
Sync map and table changes

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#133]
Climate data raster will update without running spatial analysis (which updates the tables associated with the climate data maps). This results in the data displayed in the map not matching the data displayed in the accompanying table. This could cause confusion for the user. 

The screenshot below demonstrates this issue. The map has been updated showing two climate scenarios, however, the table only shows one scenario. This is because the data is from two different data sets. This is not as easily detectable when changing between climate data sets with the same number of scenarios. 
![](https://github.com/LandSciTech/ccviR/assets/156369160/b83e3bd2-7d86-4f14-b1d7-a458d5eac300)

This may be an issue with spatial vulnerability question rasters as well, but initial tests were inconclusive, will need to test more. There is no indication in the app that the spatial vulnerability question maps/tables have been updated with a change in data (even once spatial analysis has been re-run it takes some time for the maps to update, so user could be referring to the map and/or table before it updates without knowing it). Could be helpful to add some sort of indication, even if it just labels the historical norm used to produce the data.

**Comment by adricaswell** [comment]
Further testing demonstrated that this is also an issue with spatial vulnerability questions. See image below where raster updated, but range polygon and table did not update as spatial analysis was not run. 

![image](https://github.com/LandSciTech/ccviR/assets/156369160/1fbe5aa8-7074-4f0a-a36b-f13712713c07)

**Comment by see24** [comment]
Shouldn't update until run spatial is clicked. Potentially need to overhaul reactivity of this part of the app
