### ISSUE TITLE
Document need to run spatial analysis when loading data from previous assessment

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#135]
If data is loaded from previous assessment without rerunning spatial analysis, user will not be able to see maps. Additionally, if a report is generated from a previous assessment, it will include the raw spatial data inputs, not the processed ones (see example below). To ensure the user uses the app properly, explain this in the documentation. 

<img width="414" alt="Screenshot 2024-02-29 104759" src="https://github.com/LandSciTech/ccviR/assets/156369160/9ce21021-1df9-41b4-b4f3-3becbc9351b3">

<img width="465" alt="Screenshot 2024-02-29 104854" src="https://github.com/LandSciTech/ccviR/assets/156369160/91fba243-ae55-4231-acfb-58bd8155f37f">

**Comment by adricaswell** [comment]
This need to re-run spatial analysis becomes more of an issue if a user changed their spatial vulnerability question answers from the default. Re-running spatial analysis would effectively erase their progress. To ensure users do not lose their data, this issue should either be explicitly documented or, if possible, fixed somehow.

**Comment by adricaswell** [comment]
The error message in the code block below appears when trying to load map/raster in exposure results tab without having run spatial analysis. 

```
doSpatial restore
spat out_data
Warning: Error in renderTable: climate readme file does not contain breaks for ccei
  100: stop
   99: renderTable
   98: func
   85: renderFunc
   84: output$tbl_ccei
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>
```

Tables appear to be displayed properly. Running spatial analysis resolves this error. 

This error does not appear when trying to load the spatial vulnerability question maps. The maps simply do not load.

**Comment by see24** [comment]
Make it run spatial analysis if it had already been run and then updating the spatial vuln qs from the csv
