### ISSUE TITLE
Add more information about NS CCVI/CCVAs in the app

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#146]
Provide user with more information/background about NS CCVI/CCVAs in the app so that they understand what is being calculated without referencing external documentation. Define key terms like exposure, sensitivity, and adaptive capacity. 

 Want to find a balance between providing the user with information and keeping the app clean. Ilona mentioned adding this background to the Welcome tab, but maybe we could add a "Background" tab so users can access this information without it cluttering the UI.

**Comment by see24** [comment]
Or maybe we just move the buttons for starting or loading from a saved file to the top and then have the background and detailed instructions lower down on the Welcome page?

**Comment by see24** [comment]
I think there is the right amount, the app is not the documentation
