### ISSUE TITLE
Add information to Vulnerability Questions tab

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#148]
Remind users how many vulnerability questions need to be answered to calculate the index. If the minimum is not met, inform users of this in the Index Results.

**Comment by adricaswell** [comment]
Make it clearer why some questions are "missing". Explain that the question numbers correspond with the NatureServe questions. Mention that certain questions are removed based on the taxonomic group being evaluated (and/or include all questions and grey out the ones that aren't relevant)

**Comment by plestiodon** [comment]
Wondering why Section C: 2a (sensitivity to temperature) is missing?
