### ISSUE TITLE
Display class values in the historical thermal niche table

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#149]
Display class values in the historical thermal niche table (spatial vuln question - C2ai)

Something like this:
![image](https://github.com/LandSciTech/ccviR/assets/156369160/008a45ff-3331-45ef-a03c-47332a88590f)

**Comment by adricaswell** [comment]
While working on this, look into proportion of range for historical thermal niche (guidelines don't mention proportion but proportion is used to determine the vulnerability).

I took a quick look at this since I had the app open and it looks like the sensitivity class with the greatest proportion of range in it corresponds with the vulnerability? It looks like you took a different approach compared to historical hydrological niche.

**Comment by see24** [comment]
Assigning this to @adricaswell because it is similar to what you have done for exposure

**Comment by see24** [comment]
From guidelines: "For this factor, you will overlay the range map on the historic temperature variation map and pick the highest category that includes as least 10% of the range."

Need to change to actually do this

**Comment by adricaswell** [comment]
While doing this, change this table and all other tables in the app to a gt() table.
