### ISSUE TITLE
Range change raster terminology

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#150]
Re-evaluate the terminology used for "range change raster" in the spatial data analysis tab (and any relevant documentation) to make it clearer for the user. If keeping the current terminology, add more information in spatial data analysis outlining what constitutes a range change raster. Ilona seems to have some thoughts on this so it might be worth consulting her.

**Comment by see24** [comment]
This will be addressed when popups are added for spatial data section #125
