### ISSUE TITLE
Vulnerability Question comments not saved

### ISSUE THREAD

**Issue by plestiodon** [LandSciTech/ccviR#153]
Content in the comments is not being saved.

**Comment by plestiodon** [comment]
These do get saved - after you complete a CCVI. Could they be saved before doing that or indicate that you must complete a CCVI if you want to save the comments?

**Comment by see24** [comment]
Hi Pam, 
I am not able to reproduce this error with the current version of the R package. I think I did notice it before and made changes that fixed it around March 7th. Can you try re-installing the package from GitHub with `remotes::install_github("LandSciTech/ccviR")` to ensure you have the latest version? 

If you are still having this problem after updating the package let me know and I will re-open this issue

**Comment by plestiodon** [comment]
Agree. This was fixed with the new version.
