### ISSUE TITLE
Test vulnerability score plot for multiple scenarios

### ISSUE THREAD

**Issue by adricaswell** [LandSciTech/ccviR#157]
Noticed this issue while working in app with multiple scenarios. Not sure if it is a one off or if it an actual issue. More testing needed. 
 
![image](https://github.com/LandSciTech/ccviR/assets/156369160/0b6a260a-f8dc-4f5c-aa15-9eb4008ab4a4)

**Comment by see24** [comment]
It might depend on how which vuln Qs are included because some are only shown if applicable to the species or if another is left blank

**Comment by see24** [comment]
Squished D score is when range change raster is not used a no answer given for D3 and D2 they are not included in the vulndf table. Have fixed it now

**Comment by see24** [comment]
Problem is in the plotly::subplot step when I add shareX=T it starts to be broken. Try a min reprex to see if it is a plotly thing
