### ISSUE TITLE
fix no visible binding for global variable R-CMD check notes

### ISSUE THREAD

**Issue by sebdalgarno** [LandSciTech/ccviR#178]
https://github.com/openjournals/joss-reviews/issues/7150

this might not technically be required for publication - but worth addressing I think

need to fix in dplyr and tidyr functions
data masking and tidy selection sections in [programming with dplyr](https://dplyr.tidyverse.org/articles/programming.html#tidy-selection) vignette should be useful

**Comment by see24** [comment]
Done. Just as a heads up the article you linked to isn't very helpful for this situation, maybe you meant this: [Using dplyr in packages](https://dplyr.tidyverse.org/articles/in-packages.html#data-masking-and-tidy-selection-notes)?

**Comment by sebdalgarno** [comment]
yes sorry that's the one! i.e., .data$ as you implemented
