### ISSUE TITLE
kableExtra 'namespace not imported from' R-CMD check note

### ISSUE THREAD

**Issue by sebdalgarno** [LandSciTech/ccviR#179]
https://github.com/openjournals/joss-reviews/issues/7150

might not be technically required for publication but perhaps worth addressing

`library(kableExtra)` is called in results_report.Rmd - are any kableExtra functions used?

**Comment by see24** [comment]
It seems that R-CMD check doesn't look at files in inst when it decides if the package is used. I added a reference to a kableExtra function in the R folder so it should be imported from now.
