### ISSUE TITLE
Range outline in Moisture Exposure Maps

### ISSUE THREAD

**Issue by sarahgeargeoura** [LandSciTech/ccviR#87]
Hi Sarah,

I was wondering if it was feasible/possible to thicken or darken the color of the range outline that is provided in the exposure maps. Just something I have noticed is that the range is not that visible in contrast to the darkened temperature exposure colors under the higher (RCP 8.5) emission scenario!

Thank you,
Sarah

**Comment by see24** [comment]
Thanks Sarah! Good idea
