### ISSUE TITLE
Error code on the Spatial data analysis page

### ISSUE THREAD

**Issue by kaeppich** [LandSciTech/ccviR#92]
In the shiny app the error is:
?[38;5;232m?[36mℹ?[38;5;232m In argument: `if_any(.fun = ~!is.na(.x))`.?[39m ?[1mCaused by error in `across()`:?[22m ?[38;5;232m?[33m!?[38;5;232m `...` 

In R the error is:
performing spatial analysis
exact_extract may perform poorly when extracting from a RasterStack. It is recommended to use a SpatRaster from the terra package instead. Convert using terra::rast(x)
Warning: Error in : ℹ In argument: `if_any(.fun = ~!is.na(.x))`.
Caused by error in `across()`:
! `...` must be empty.
✖ Problematic argument:
• .fun = ~!is.na(.x)
  100: stop
   99: renderText
   98: func
   85: renderFunc
   84: output$spat_error
    3: runApp
    2: print.shiny.appobj
    1: <Anonymous>

This error shows up in the demo as well.

**Comment by see24** [comment]
Hi @kaeppich thanks for reporting this error. 
I think I had introduced a typo recently, should be working now. You will need to re-install the package from GitHub. 

Also, can I ask who you are and what you are using the package for? Just interested to know what people are using it for and we are trying to keep track of users to help show the project is useful.

Thanks!

**Comment by kaeppich** [comment]
I am a co-op student working on species at risk recovery and conservation :)
